import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
    safeArea: {
      flex: 1,
      backgroundColor: '#121212',
    },
    container: {
      flex: 1,
      padding: 16,
      paddingTop: 32,
    },
    title: {
      fontSize: 36,
      fontWeight: 'bold',
      color: '#FFA500',
      marginBottom: 24,
      alignSelf: 'flex-start',
      fontFamily: 'Pacifico',
    },
    createContainer: {
      flexDirection: 'row',
      marginBottom: 16,
    },
    input: {
      flex: 1,
      height: 48,
      borderColor: '#555',
      borderWidth: 1,
      paddingHorizontal: 12,
      color: '#FFFFFF',
      backgroundColor: '#333',
      borderRadius: 8,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.2,
      shadowRadius: 2,
      elevation: 2,
    },
    createButton: {
      marginLeft: 8,
      backgroundColor: '#FFA500',
      paddingHorizontal: 16,
      justifyContent: 'center',
      alignItems: 'center',
      borderRadius: 8,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.2,
      shadowRadius: 2,
      elevation: 2,
    },
    createButtonText: {
      color: '#121212',
      fontWeight: 'bold',
    },
    sectionTitle: {
      fontSize: 20,
      fontWeight: 'bold',
      color: '#FFFFFF',
      marginTop: 16,
      marginBottom: 12,
    },
    loadingContainer: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
    },
    emptyContainer: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
      marginTop: 50,
    },
    emptyText: {
      color: '#888',
      fontSize: 16,
    },
    boardRow: {
      justifyContent: 'space-between',
      marginVertical: 8,
    },
    boardCard: {
      width: '48%',
      height: 150,
      backgroundColor: '#1f1f1f',
      borderRadius: 8,
      padding: 16,
      justifyContent: 'center',
      alignItems: 'center',
      position: 'relative',
      borderWidth: 1,
      borderColor: '#333',
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.3,
      shadowRadius: 3,
      elevation: 3,
      marginBottom: 8,
    },
    boardName: {
      color: '#FFFFFF',
      fontSize: 18,
      fontWeight: 'bold',
      textAlign: 'center',
      marginBottom: 8,
    },
    boardDesc: {
      color: '#BBBBBB',
      fontSize: 14,
      textAlign: 'center',
    },
    boardActions: {
      position: 'absolute',
      top: 8,
      right: 8,
      flexDirection: 'row',
    },
    editButton: {
      padding: 5,
      marginRight: 5,
    },
    deleteButton: {
      padding: 5,
    },
    modalOverlay: {
      flex: 1,
      backgroundColor: 'rgba(0, 0, 0, 0.7)',
      justifyContent: 'center',
      alignItems: 'center',
    },
    modalContent: {
      width: '80%',
      backgroundColor: '#1f1f1f',
      borderRadius: 12,
      padding: 20,
      borderWidth: 1,
      borderColor: '#333',
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.5,
      shadowRadius: 5,
      elevation: 5,
    },
    modalTitle: {
      color: '#FFA500',
      fontSize: 18,
      fontWeight: 'bold',
      marginBottom: 16,
      textAlign: 'center',
    },
    modalInput: {
      backgroundColor: '#333',
      color: '#FFFFFF',
      padding: 12,
      borderRadius: 8,
      borderWidth: 1,
      borderColor: '#555',
      marginBottom: 16,
    },
    modalButtons: {
      flexDirection: 'row',
      justifyContent: 'space-between',
    },
    modalButton: {
      paddingVertical: 10,
      paddingHorizontal: 16,
      borderRadius: 8,
      flex: 1,
      marginHorizontal: 5,
      alignItems: 'center',
    },
    cancelButton: {
      backgroundColor: '#444',
    },
    saveButton: {
      backgroundColor: '#FFA500',
    },
  modalButtonText: {
    color: '#FFF',
    fontWeight: 'bold',
  },
  templateItem: {
    padding: 15,
    borderBottomWidth: 1,
    borderBottomColor: '#eee',
  },
  templateTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#333',
  },
  templateDescription: {
    fontSize: 14,
    color: '#666',
    marginTop: 5,
  },
  });
