import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
    safeArea: {
      flex: 1,
      backgroundColor: '#121212',
    },
    container: {
      flex: 1,
      padding: 16,
      paddingTop: 32,
    },
    title: {
      fontSize: 36,
      fontWeight: 'bold',
      color: '#FFA500',
      marginBottom: 24,
      marginTop:18,
      alignSelf: 'flex-start',
      fontFamily: 'Pacifico',
    },
    sectionTitle: {
      fontSize: 20,
      fontWeight: 'bold',
      color: '#FFA500',
      marginTop: 16,
      marginBottom: 12,
    },
    createContainer: {
      flexDirection: 'row',
      marginBottom: 16,
    },
    input: {
      flex: 1,
      height: 48,
      borderColor: '#555',
      borderWidth: 1,
      paddingHorizontal: 12,
      color: '#FFFFFF',
      backgroundColor: '#333',
      borderRadius: 8,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.2,
      shadowRadius: 2,
      elevation: 2,
    },
    createButton: {
      marginLeft: 8,
      backgroundColor: '#FFA500',
      paddingHorizontal: 16,
      justifyContent: 'center',
      alignItems: 'center',
      borderRadius: 8,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.2,
      shadowRadius: 2,
      elevation: 2,
    },
  createButtonText: {
    color: '#FFF',
    fontWeight: 'bold',
  },
  headerContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    width: '100%',
    marginBottom: 15,
  },
    workspaceItemContainer: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      padding: 16,
      borderBottomWidth: 1,
      borderBottomColor: '#555',
      marginVertical: 4,
      backgroundColor: '#1f1f1f',
      borderRadius: 8,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.2,
      shadowRadius: 2,
      elevation: 2,
    },
    workspaceItem: {
      flex: 1,
      color: '#FFFFFF',
      fontSize: 16,
    },
    actionsContainer: {
      flexDirection: 'row',
      alignItems: 'center',
    },
    editButton: {
      padding: 8,
      marginRight: 8,
    },
    editButtonText: {
      fontSize: 18,
    },
    deleteButton: {
      padding: 8,
    },
    deleteButtonText: {
      fontSize: 18,
    },
    modalContainer: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
      backgroundColor: 'rgba(0, 0, 0, 0.7)',
    },
    modalContent: {
      width: '85%',
      backgroundColor: '#1f1f1f',
      padding: 24,
      borderRadius: 12,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.3,
      shadowRadius: 4,
      elevation: 8,
    },
    modalTitle: {
      fontSize: 20,
      fontWeight: 'bold',
      color: '#FFFFFF',
      marginBottom: 16,
      textAlign: 'center',
    },
    modalInput: {
      height: 48,
      borderColor: '#555',
      borderWidth: 1,
      marginBottom: 20,
      paddingHorizontal: 12,
      color: '#FFFFFF',
      backgroundColor: '#333',
      borderRadius: 8,
    },
    modalButtonsContainer: {
      flexDirection: 'row',
      justifyContent: 'space-between',
    },
    modalButton: {
      flex: 1,
      paddingVertical: 12,
      borderRadius: 8,
      alignItems: 'center',
      justifyContent: 'center',
    },
    cancelButton: {
      backgroundColor: '#444',
      marginRight: 8,
    },
    updateButton: {
      backgroundColor: '#1E90FF',
      marginLeft: 8,
    },
    modalButtonText: {
      color: '#FFFFFF',
      fontWeight: 'bold',
    },
    emptyContainer: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
      marginTop: 50,
    },
    emptyText: {
      color: '#888',
      fontSize: 16,
    },
  });
